[package]
name = "perform_wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.23.0", default-features = false, features = ["sync"] }
once_cell = "1.16.0"
wasm-bindgen-futures = "0.4.33"
